// libs/shared/errors/src/lib/exception.codes.ts
export const GENERIC_ARGUMENT_INVALID = 'GENERIC.ARGUMENT_INVALID';
export const GENERIC_ARGUMENT_OUT_OF_RANGE = 'GENERIC.ARGUMENT_OUT_OF_RANGE';
export const GENERIC_ARGUMENT_NOT_PROVIDED = 'GENERIC.ARGUMENT_NOT_PROVIDED';
export const GENERIC_NOT_FOUND = 'GENERIC.NOT_FOUND';
export const GENERIC_CONFLICT = 'GENERIC.CONFLICT';
export const GENERIC_INTERNAL_SERVER_ERROR = 'GENERIC.INTERNAL_SERVER_ERROR';
export const GENERIC_UNAUTHORIZED = 'GENERIC.UNAUTHORIZED';
export const GENERIC_FORBIDDEN = 'GENERIC.FORBIDDEN';
